console.log('Hello world');

// CLASS NOTES

// Declaración de variables
var dog = "Max";

// Concatenación
console.log("The name of the dog is: " + dog);

// Tipos de datos PRIMITIVOS

// STRING
// NUMBER
// BOOLEAN
// UNDEFINED
// NULL 
// SYMBOL 
// BIGINT

// Primitivos
let nombre = "Pablo";       // String
let edad = 25;              // Number
let activo = true;          // Boolean
let mascota;                // Undefined
let valor = null;           // Null
let simbolo = Symbol("id"); // Symbol
let numeroGrande = 9007199254740991n; // BigInt

// Operadores matematicos

// + - / * 

// Operadores matematicos de comparacion

// > < ==

// 
